"""Initial migration

Revision ID: 0ce8ef8621c5
Revises: 
Create Date: 2020-03-02 16:34:07.576151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce8ef8621c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # -----------------------------------------------------------------------
    # inconsistencies in the course videos and code needed or db values
    #op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    #op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persons_pkey')
    )
    # ### end Alembic commands ###
